spring:
  profiles:
    active:
      - redis
  redis:
    port: 6379
    host: localhost
  data:
    mongodb:
      database: honganhdb
      host: localhost
      port: 27017
server:
  port: 8081
kafka:
  producer:
    bootstrap: localhost:9092
    topic: workunits